baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Scula Castel Corno"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/2014_0621-22-cevedale-sdim0025-star_.jpg"]