# when using the default proxy server port
local_backend: true
# to start local decap server: npx decap-server

backend:
  name: git-gateway
  repo: marcorobol/one-click-hugo-cms
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit

  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "course" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Course" # Used in the UI, ie.: "New Course"
    folder: "site/content/course" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        date_format: "MMMM YYYY" # e.g. February 2021
        picker_utc: false
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "pages"
    label: "Pages"
    files:

      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - label: "Corsi in evidenza"
            name: corsi
            widget: list
            field:
              label: "Corso"
              name: "corso"
              widget: "relation"
              collection: "course"
              value_field: "title"
              search_fields: ["title", "date"]
              display_fields: ["title", "date"]
      
      - file: "site/content/scuola/_index.md"
        label: "La scuola"
        name: "scuola"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
      
      - file: "site/content/organico/_index.md"
        label: "Organico"
        name: "organico"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
      
      - file: "site/content/contact/_index.md"
        label: "Contatti"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
  
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: text}
      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
